export const DEMO_STATS = {
  total_leads: 47,
  new_leads: 12,
  qualified_leads: 8,
  avg_confidence: 0.72,
  leads_this_week: 15,
  top_services: [
    { service: 'knowledge_systems', count: 18 },
    { service: 'digital_tools', count: 14 },
    { service: 'interactive_tools', count: 9 },
    { service: 'custom_applications', count: 7 },
    { service: 'digital_storytelling', count: 5 },
  ],
  source_breakdown: [
    { source: 'Philanthropy News Digest', count: 15 },
    { source: 'RFPMart — IT Services', count: 11 },
    { source: 'Grants.gov', count: 9 },
    { source: 'RFPMart — Consulting', count: 7 },
    { source: 'Nonprofit Quarterly', count: 5 },
  ],
};

export const DEMO_LEADS = [
  {
    id: 1, created_at: '2026-02-20T10:30:00', org_name: 'National Education Association',
    org_type: 'association', title: 'RFP: Knowledge Management Platform Modernization',
    summary: 'NEA seeks a vendor to redesign their internal knowledge management system serving 3M+ members. They cite fragmented data silos and need for unified search.',
    source_url: '#', source_type: 'rss_rfp', source_name: 'Philanthropy News Digest',
    confidence_score: 0.92, relevance_reasoning: 'Strong match — explicit KM modernization from a major professional association.',
    service_matches: ['knowledge_systems', 'digital_tools'],
    intent_signals: ['data silos', 'knowledge management', 'modernization'],
    status: 'new', notes: null,
  },
  {
    id: 2, created_at: '2026-02-19T14:15:00', org_name: 'Ford Foundation',
    org_type: 'foundation', title: 'Grant: Interactive Data Dashboard for Inequality Research',
    summary: 'Ford Foundation awarded $2.3M for an interactive public dashboard visualizing inequality metrics.',
    source_url: '#', source_type: 'grants_gov', source_name: 'Grants.gov',
    confidence_score: 0.87, relevance_reasoning: 'Interactive dashboard project — exactly our Interactive Tools service line.',
    service_matches: ['interactive_tools', 'digital_storytelling', 'custom_applications'],
    intent_signals: ['interactive dashboard', 'data visualization'],
    status: 'new', notes: null,
  },
  {
    id: 3, created_at: '2026-02-19T09:00:00', org_name: 'American Bar Association',
    org_type: 'association', title: 'RFP: Digital Transformation of Legal Research Portal',
    summary: 'ABA seeking a complete overhaul of their legal research portal — "fragmented, siloed databases."',
    source_url: '#', source_type: 'rss_rfp', source_name: 'RFPMart — IT Services',
    confidence_score: 0.85, relevance_reasoning: 'Clear digital transformation need. Strong alignment with Knowledge Systems.',
    service_matches: ['knowledge_systems', 'digital_tools', 'custom_applications'],
    intent_signals: ['digital transformation', 'fragmented systems', 'data silos'],
    status: 'reviewing', notes: 'Reviewed by Sarah — strong fit. ABA has budget.',
  },
  {
    id: 4, created_at: '2026-02-18T16:45:00', org_name: 'Sierra Club Foundation',
    org_type: 'foundation', title: 'Interactive Storytelling Platform for Climate Impact',
    summary: 'Looking for a partner to build an interactive digital storytelling experience around climate impact data.',
    source_url: '#', source_type: 'rss_rfp', source_name: 'Philanthropy News Digest',
    confidence_score: 0.81, relevance_reasoning: 'Direct match for Digital Storytelling. Foundation with clear budget.',
    service_matches: ['digital_storytelling', 'interactive_tools'],
    intent_signals: ['digital storytelling', 'data visualization'],
    status: 'qualified', notes: 'Great fit. Sending intro email.',
  },
  {
    id: 5, created_at: '2026-02-18T11:20:00', org_name: 'National Council of Nonprofits',
    org_type: 'ngo', title: 'RFI: Custom Member Dashboard Application',
    summary: 'NCN issuing RFI for a dashboard aggregating state nonprofit policy data and resource libraries.',
    source_url: '#', source_type: 'rss_rfp', source_name: 'RFPMart — Consulting',
    confidence_score: 0.78, relevance_reasoning: 'Custom application with data aggregation. Good fit.',
    service_matches: ['custom_applications', 'interactive_tools', 'knowledge_systems'],
    intent_signals: ['custom application', 'interactive dashboard'],
    status: 'new', notes: null,
  },
  {
    id: 6, created_at: '2026-02-17T08:00:00', org_name: 'Brookings Institution',
    org_type: 'foundation', title: 'Digital Tools for Policy Research Dissemination',
    summary: 'Exploring new digital tools to make policy research more accessible for non-expert audiences.',
    source_url: '#', source_type: 'rss_news', source_name: 'Nonprofit Quarterly',
    confidence_score: 0.64, relevance_reasoning: 'Moderate signal — no formal RFP yet. Worth monitoring.',
    service_matches: ['digital_storytelling', 'digital_tools'],
    intent_signals: ['digital transformation'],
    status: 'new', notes: null,
  },
  {
    id: 7, created_at: '2026-02-16T14:30:00', org_name: 'Robin Hood Foundation',
    org_type: 'foundation', title: 'Grant: Technology Capacity Building for NYC Nonprofits',
    summary: 'Robin Hood awarded $5M for tech capacity across NYC grantees — custom tools, data, and KM.',
    source_url: '#', source_type: 'grants_gov', source_name: 'Grants.gov',
    confidence_score: 0.73, relevance_reasoning: 'Large grant with explicit tech/KM spending.',
    service_matches: ['knowledge_systems', 'digital_tools', 'custom_applications'],
    intent_signals: ['knowledge management', 'technology upgrade'],
    status: 'new', notes: null,
  },
];
